### PR TITLE
Update CI to use release 5.10 image

### PR DESCRIPTION
**Pull request by glbrntt**

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
@swift-server-bot add to allowlist

**Comment by glbrntt** [comment]
5.10 is failing because strict concurrency checking and warnings as errors are enabled. 

The concurrency checking emits a warning because of the generated test file which contains a static array of test classes, and `XCTestCase` isn't `Sendable`.

Do you have a preference for which option to disable?

**Comment by czechboy0** [comment]
> contains a static array of test classes

Maybe we can just move it to be a fileprivate global let in the file, to avoid coupling it to the (non-Sendable) XCTestCase subclass?

**Comment by glbrntt** [comment]
I disabled strict concurrency checking for now and filed https://github.com/apple/swift-openapi-generator/issues/543 to re-enable it.

I also filed a radar against SwiftPM.

**Review by czechboy0 — APPROVED** [review]
Thanks @glbrntt!

**Pull request merged**
